project_id = "ysqqnkbgkrjoxrzlejxy"

[functions.check-email]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.admin-reset-mfa]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.force-password-reset]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.api-salesheader]
verify_jwt = false

[functions.api-salesline]
verify_jwt = false

[functions.api-payment]
verify_jwt = false

[functions.api-customer]
verify_jwt = false

[functions.api-supplier]
verify_jwt = false

[functions.api-supplierproduct]
verify_jwt = false

[functions.api-brand]
verify_jwt = false

[functions.api-product]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.handle-ticket-action]
verify_jwt = false

[functions.extract-closing-number]
verify_jwt = false

[functions.extract-shift-closing-number]
verify_jwt = false

[functions.extract-ludo-transaction]
verify_jwt = false

[functions.sync-brand-to-odoo]
verify_jwt = false

[functions.sync-product-to-odoo]
verify_jwt = false

[functions.upload-to-cloudinary]
verify_jwt = false

[functions.migrate-shift-images-to-cloudinary]
verify_jwt = false

[functions.send-reorder-notification]
verify_jwt = false

[functions.sync-order-to-odoo]
verify_jwt = false

[functions.sync-customer-to-odoo]
verify_jwt = false

[functions.sync-all-products-to-odoo]
verify_jwt = false

[functions.sync-order-to-odoo-step]
verify_jwt = false

[functions.send-task-notification]
verify_jwt = false

[functions.pdf-to-excel]
verify_jwt = false

[functions.sync-orders-background]
verify_jwt = false

[functions.external-supabase-proxy]
verify_jwt = false

[functions.verify-sysadmin]
verify_jwt = false

[functions.detect-password-anomalies]
verify_jwt = false

[functions.generate-user-certificate]
verify_jwt = false

[functions.validate-user-certificate]
verify_jwt = false

[functions.backup-database-background]
verify_jwt = false

[functions.test-email-connection]
verify_jwt = false

[functions.sync-emails-background]
verify_jwt = false

[functions.api-zk-attendance]
verify_jwt = false

[functions.sync-orders-daily-background]
verify_jwt = false

[functions.migrate-bank-ledger-hyperpay]
verify_jwt = false
