project_id = "ysqqnkbgkrjoxrzlejxy"

[functions.check-email]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.admin-reset-mfa]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.force-password-reset]
verify_jwt = false
