project_id = "ysqqnkbgkrjoxrzlejxy"

[functions.check-email]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.admin-reset-mfa]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.force-password-reset]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.api-salesheader]
verify_jwt = false

[functions.api-salesline]
verify_jwt = false

[functions.api-payment]
verify_jwt = false

[functions.api-customer]
verify_jwt = false

[functions.api-supplier]
verify_jwt = false

[functions.api-supplierproduct]
verify_jwt = false

[functions.api-brand]
verify_jwt = false

[functions.api-product]
verify_jwt = false
